apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-webserver
  namespace: <your-namespace> # Your namespace here
  labels:
    app: chat-app-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-webserver
  template:
    metadata:
      labels:
        app: chat-app-webserver
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: chat-app-webserver
          image: 700935310038.dkr.ecr.us-east-1.amazonaws.com/chat-app-webserver:0.0.2
          env:
            - name: AWS_REGION   # region of SQS queue
              value: <sqs-region>
            - name: QUEUE_NAME
              value: <sqs-queue-name>
            - name: SQL_HOST
              value: <mysql-db-name>
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-webserver-service
  namespace: <your-namespace>
spec:
  selector:
    app: chat-app-webserver
  ports:
    - port: 8080
      targetPort: 8080
