apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-worker
  namespace: alonit-ns # Your namespace here
  labels:
    app: chat-app-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app-worker
  template:
    metadata:
      labels:
        app: chat-app-worker
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: chat-app-worker
          image: 700935310038.dkr.ecr.us-east-1.amazonaws.com/chat-app-worker:0.0.1
          env:
            - name: BUCKET_NAME
              value: iec-alonit-22
            - name: AWS_REGION   # region of SQS queue
              value: eu-north-1
            - name: QUEUE_NAME
              value: alonit-queue
          resources:
            limits:
              cpu: "50m"
            requests:
              cpu: "10m"
