apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-webserver
  namespace: alonit-ns # Your namespace here
  labels:
    app: chat-app-webserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chat-app-webserver
  template:
    metadata:
      labels:
        app: chat-app-webserver
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: chat-app-webserver
          image: 700935310038.dkr.ecr.us-east-1.amazonaws.com/chat-app-webserver:0.0.1
          env:
            - name: AWS_REGION   # region of SQS queue
              value: eu-north-1
            - name: QUEUE_NAME
              value: alonit-queue
            - name: SQL_HOST
              value: alonit-db.c34a2z7p5ba9.eu-north-1.rds.amazonaws.com
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
