pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo building ${BUILD_TAG}'
            }
        }
        stage('Test') {
            steps {
                sh ''
            }
        }
        stage('Deploy') {
            steps {
                sh ''
            }
        }


//         stage ('Starting ART job') {
//             steps {
//                 build job: 'test',
//                 parameters: [
//                     string(name: 'docker image', value: 'docker')
//                 ],
//                 wait: false
//             }
//         }
    }
}