pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh ''
            }
        }
        stage('Test') {
            steps {
                sh ''
            }
        }
        stage('Deploy') {
            steps {
                sh ''
            }
        }
        stage ('Starting ART job') {
            steps {
                build job: 'your-job-name',
                parameters: [
                    string(name: 'docker image', value: 'docker')
                ]
            }
        }
    }
}