pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'set'
            }
        }
        stage('Test') {
            steps {
                sh 'echo testing'
            }
        }
        stage('Deploy') {
            steps {
                sh ''
            }
        }
    }
}